const ENGINE_CONTRACT = "engineContract";
const ACCOUNT_NFT_CONTRACT = "accountNftContract";
const ERC6551_REGISTRY_CONTRACT = "erc6551Registry";
const EEG_CONTRACT = "EEGToken";
const GAME_ASSETS_NFT_CONTRACT = "GameAssetsNFT";
const ERC6551_ACCOUNT = "erc6551Account";

export {
  ENGINE_CONTRACT,
  ACCOUNT_NFT_CONTRACT,
  ERC6551_REGISTRY_CONTRACT,
  EEG_CONTRACT,
  GAME_ASSETS_NFT_CONTRACT,
  ERC6551_ACCOUNT,
};
